### ISSUE TITLE
nethogs 0.8.7 build issue

### ISSUE THREAD

**Issue by chenrui333** [raboof/nethogs#225]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>build error</summary>

```
clang++  -Wall -Wextra -Wno-missing-field-initializers -c cui.cpp -DVERSION=\"0.8.7\"
clang++  -Wall -Wextra -Wno-missing-field-initializers -c inode2prog.cpp
clang++  -Wall -Wextra -Wno-missing-field-initializers -c conninode.cpp
clang++ -Wall -Wextra -Wno-missing-field-initializers   -c -o devices.o devices.cpp
cui.cpp:72:1: error: unknown type name 'constexpr'
constexpr char FILE_SEPARATOR = '/';
^
connection.cpp:162:23: error: no matching member function for call to 'lower_bound'
  auto it = connList->lower_bound(&p);
            ~~~~~~~~~~^~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/c++/v1/set:1350:14: note: candidate function not viable: no known conversion from 'Packet *' to 'const std::multiset<Connection *, ConnectionComparator>::key_type' (aka 'Connection *const') for 1st argument
    iterator lower_bound(const key_type& __k)
             ^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/c++/v1/set:1353:20: note: candidate function not viable: no known conversion from 'Packet *' to 'const std::multiset<Connection *, ConnectionComparator>::key_type' (aka 'Connection *const') for 1st argument
    const_iterator lower_bound(const key_type& __k) const
                   ^
connection.cpp:187:23: error: no matching member function for call to 'lower_bound'
  auto it = connList->lower_bound(packet);
            ~~~~~~~~~~^~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/c++/v1/set:1350:14: note: candidate function not viable: no known conversion from 'Packet *' to 'const std::multiset<Connection *, ConnectionComparator>::key_type' (aka 'Connection *const') for 1st argument
    iterator lower_bound(const key_type& __k)
             ^
/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/c++/v1/set:1353:20: note: candidate function not viable: no known conversion from 'Packet *' to 'const std::multiset<Connection *, ConnectionComparator>::key_type' (aka 'Connection *const') for 1st argument
    const_iterator lower_bound(const key_type& __k) const
                   ^
1 error generated.
make[1]: *** [cui.o] Error 1
make[1]: *** Waiting for unfinished jobs....
2 errors generated.
make[1]: *** [connection.o] Error 1
make: *** [install] Error 2
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/runs/5840476457
relates to Homebrew/homebrew-core#98555

**Comment by raboof** [comment]
Interesting!

I don't have a mac so I can't really test with that.

I see it's also failing on Ubuntu Xenial (from 2016, with gcc 5.4.0). It might be nice to support that but it's rather old, so if it's tricky then I'm OK with not supporting it.

> constexpr char FILE_SEPARATOR = '/';

introduced in b94cd9f2275e4bdceec313d36af55af4e8e59b64 /cc @sgtcortez 

> auto it = connList->lower_bound(packet);

introduced in 92fb73116a4f70da21c001f4435e735ecb79473f /cc @CyberShadow

**Comment by CyberShadow** [comment]
Yep, you need a C++14-compliant compiler to support `is_transparent`.

It's possible that the compiler you have might support it, but needs a compiler switch to enable it.

**Comment by raboof** [comment]
weird though, the CI logs claims it's using Clang 13.1.6 build 1316, and I didn't have to pass any custom switches to support it at least on 13.0.1 (on Linux)

**Comment by sgtcortez** [comment]
Have you tried add the flag: `std=c++14` ?

**Comment by msbit** [comment]
> weird though, the CI logs claims it's using Clang 13.1.6 build 1316, and I didn't have to pass any custom switches to support it at least on 13.0.1 (on Linux)

As per https://en.wikipedia.org/wiki/Xcode#Toolchain_versions Clang bundled with the Apple toolchain reports different versions, so (presuming the brew CI parses what `c++ --version` says) the actual version of Clang is likely around 12.0.0 which may not default to C++14 ✌️
